if(window.top!==window.self){document.querySelector('#app').textContent='Open Coffee Circle directly in its own browser tab.';throw new Error('Embedded app access blocked.');}
const app=document.querySelector('#app');
let lang=sessionStorage.getItem('language')||'en',menu,group,own,cart=[],busy=false,view='';
let groupId,access,orderId,isAdmin,organizerSession='';
const frontendBase=new URL('./',location.href);frontendBase.hash='';frontendBase.search='';
const configured=window.COFFEE_CONFIG?.apiBase||'';
const apiBase=configured?new URL(configured):new URL(location.origin);
if(!['http:','https:'].includes(apiBase.protocol)||apiBase.username||apiBase.password||apiBase.search||apiBase.hash||apiBase.pathname!=='/')throw new Error('API configuration must be an HTTPS origin without credentials, path, query or fragment.');
if(apiBase.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(apiBase.hostname))throw new Error('API configuration must use HTTPS outside loopback development.');
const setRoute=()=>{const p=new URLSearchParams(location.hash.slice(1));const next=p.get('g'),nextKey=p.get('a');if(groupId!==next||access!==nextKey)organizerSession='';groupId=next;access=nextKey;orderId=p.get('o');isAdmin=p.get('mode')==='admin';};
setRoute();
const text=(en,zh)=>lang==='en'?en:zh;
const el=(tag,content,cls)=>{const e=document.createElement(tag);if(content!==undefined)e.textContent=content;if(cls)e.className=cls;return e};
const random=()=>[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');
const button=(label,fn,quiet=false)=>{const b=el('button',label,quiet?'quiet':'');b.type='button';b.addEventListener('click',fn);return b};
const error=(message,c=app)=>{c.querySelector('.error')?.remove();const p=el('p',message,'error');p.setAttribute('role','alert');c.append(p);p.scrollIntoView({block:'nearest',behavior:'smooth'})};
const feedback=(message,c)=>{c.querySelector('.feedback')?.remove();c.append(el('p',message,'success feedback'))};
const field=(parent,title,input)=>{const label=el('label',title);input.id='f-'+crypto.randomUUID();label.htmlFor=input.id;parent.append(label,input);return input};
const select=(values,labels)=>{const s=el('select');values.forEach((v,i)=>{const o=el('option',labels?.[i]||v);o.value=v;s.append(o)});return s};
const api=async(path,method='GET',body,token=access)=>{let r;try{r=await fetch(new URL(path,apiBase),{method,credentials:'omit',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(isAdmin&&organizerSession?{'X-Organizer-Session':organizerSession}:{})},...(body?{body:JSON.stringify(body)}:{})})}catch{throw new Error(text('Connection interrupted. Your draft is saved; retry when connected.','連線中斷。草稿已保留，連線恢復後可重試。'))}let data;try{data=await r.json()}catch{throw new Error(text('Server unavailable. Please retry.','伺服器暫時無法使用，請重試。'))}if(!r.ok)throw Object.assign(new Error(data.error),{status:r.status});return data};
const localTime=s=>new Date(s).toLocaleString(lang==='en'?'en-HK':'zh-HK',{timeZone:'Asia/Macau',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})+' · '+text('Macau time','澳門時間');
const toInput=s=>new Date(Date.parse(s)+8*3600000).toISOString().slice(0,16);
const fromInput=s=>{const d=new Date(s+':00+08:00');if(!Number.isFinite(d.valueOf()))throw new Error(text('Choose a valid cutoff time.','請選擇有效截單時間。'));return d.toISOString()};
const defaultCutoff=()=>{const now=Date.now(),shifted=new Date(now+8*3600000),boundary=Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate(),15,59);return new Date(Math.min(now+3600000,boundary-60000)>now?Math.min(now+3600000,boundary-60000):now+86400000).toISOString()};
const valueName=v=>lang==='en'?v:({'Tall':'中杯','Grande':'大杯','Venti':'特大杯','Hot':'熱','Iced':'凍','Blended':'冰沙','Original recipe':'原配方','Oat requested':'希望轉燕麥奶','Soy requested':'希望轉豆奶','Less sweet requested':'希望少甜'}[v]||v);
const drinkName=id=>{const d=menu.drinks.find(d=>d.id===id);return d?lang==='en'?d.en:d.zh:id};
const variantKey=i=>JSON.stringify([i.drink,i.size,i.temperature,i.milk,i.sweetness]);
const itemName=i=>`${drinkName(i.drink)} · ${[i.size,i.temperature,i.milk,i.sweetness].map(valueName).join(' · ')}`;
const link=(token,extra={})=>frontendBase.href+'#'+new URLSearchParams({g:groupId,a:token,...extra});
const navigate=(url,session='')=>{const next=new URL(url);history.pushState(null,'',next);setRoute();organizerSession=session;group=null;own=null;cart=[];draft=null;busy=false;if(groupId&&access)refresh();else home();};
const routeChanged=()=>{setRoute();group=null;own=null;cart=[];draft=null;busy=false;if(groupId&&access)refresh();else home();};
window.addEventListener('hashchange',routeChanged);window.addEventListener('popstate',routeChanged);
const intro=(title,lead)=>{app.replaceChildren(el('div',text('COFFEE, WITH YOUR PEOPLE','一杯咖啡，一起分享'),'eyebrow'),el('h1',title),el('p',lead,'lead'))};
const notice=()=>el('p',text('Independent group collection, not an official Starbucks service. Your organizer buys and brings back the drinks. Drink names reference Hong Kong official sources; preferences and Macau availability need store confirmation.','獨立團購登記工具，非 Starbucks 官方訂購服務。主辦者購買後帶回並按姓名分發。飲品名称參考香港官方資料；飲品、杯型及客製偏好以門市當日供應為準。'),'note');
const retentionNotice=()=>el('p',text('Names, requests and distribution status clear daily at 23:59 Macau time. Group settings and catalog remain. Save any needed list before then.','姓名、登記及分發狀態每天澳門時間 23:59 清除；群組設定及飲品目錄保留。如需保留清單，請於清除前另存。'),'small');
const draftKey=()=>`coffee-draft:${groupId}:${isAdmin?'extra':orderId||'join'}`;
let draft;function loadDraft(){try{draft=JSON.parse(sessionStorage.getItem(draftKey())||'null');if(draft?.expiresAt&&draft.expiresAt<=group.serverTime){sessionStorage.removeItem(draftKey());draft=null}}catch{draft=null}}
function saveDraft(name){draft={...draft,name,items:cart,requestId:draft?.requestId||crypto.randomUUID(),editToken:draft?.editToken||random(),expiresAt:group.nextPurge};sessionStorage.setItem(draftKey(),JSON.stringify(draft))}
async function copy(s,c){try{await navigator.clipboard.writeText(s);feedback(text('Copied.','已複製。'),c)}catch{const box=el('textarea');box.value=s;box.readOnly=true;c.append(box);box.select();error(text('Select and copy this text manually.','請選取並手動複製文字。'),c)}}
function home(){view='home';intro(text('Good coffee.\nGreat company.','一起分享\n好咖啡。'),text('A simple link for the next coffee run. Everyone chooses; one organizer buys, brings back, and distributes.','一條連結收集大家的飲品偏好，由一位主辦者統一購買、帶回及分發。'));
 const layout=el('div',undefined,'layout'),card=el('form',undefined,'card'),aside=el('aside',undefined,'card hero-side');layout.append(card,aside);app.append(layout);card.append(el('h2',text('Create your group','建立群組')));
 const title=field(card,text('Group name','群組名稱'),el('input'));title.required=true;title.maxLength=80;title.placeholder=text('Friday team coffee','星期五團隊咖啡');
 const welcome=field(card,text('Welcome message for participants','給參加者的歡迎訊息'),el('textarea'));welcome.maxLength=500;welcome.placeholder=text('I’ll bring your drinks back to the office.','我會把飲品帶回辦公室。');
 const privateBox=el('section',undefined,'private-box');card.append(privateBox);privateBox.append(el('span',text('ORGANIZER ONLY','只供主辦者'),'eyebrow'));
 const region=field(privateBox,text('Purchase region','購買地區'),select(['HK','MO'],[text('Hong Kong · HKD','香港 · HKD'),text('Macau · MOP','澳門 · MOP')]));
 const store=field(privateBox,text('Store / purchase location','門市 / 購買地點'),el('input'));store.required=true;store.maxLength=120;
 const cutoff=field(privateBox,text('Order cutoff (Macau time, UTC+8)','截單時間（澳門時間 UTC+8）'),el('input'));cutoff.type='datetime-local';cutoff.required=true;cutoff.value=toInput(defaultCutoff());
 const pw=field(privateBox,text('Set organizer password (8+ characters)','設定主辦者密碼（至少 8 字元）'),el('input'));pw.type='password';pw.minLength=8;pw.maxLength=128;pw.required=true;pw.autocomplete='new-password';
 privateBox.append(el('p',text('Choose your own password. It stays off share links. Keep your private organizer link and password; refreshing locks the desk. There is no email recovery.','請自行設定密碼。分享連結不包含密碼。請保管私人主辦者連結及密碼；重新載入會鎖定工作台。此工具沒有電郵重設功能。'),'small'));
 const submit=el('button',text('Create coffee circle →','建立飲品群組 →'));submit.type='submit';const createActions=el('div',undefined,'actions');createActions.append(submit);card.append(createActions);
 card.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;try{const r=await api('/api/groups','POST',{title:title.value,welcome:welcome.value,region:region.value,store:store.value,cutoff:fromInput(cutoff.value),password:pw.value},null);pw.value='';navigate(frontendBase.href+'#'+new URLSearchParams({g:r.id,a:r.admin,mode:'admin'}),r.sessionToken)}catch(e){error(e.message,card);busy=false;submit.disabled=false}});
 aside.append(el('h2',text('One coffee run.\nEveryone included.','一趟購買，\n照顧每個人。')),el('p',text('Choose → collect requests → buy → distribute by name. No participant account, store selection, or payment step.','選飲品 → 收集登記 → 購買 → 按姓名分發。參加者毋須帳戶，也毋須選門市或付款。')),notice(),retentionNotice());
}
function login(){view='login';intro(text('Your organizer desk.','主辦者工作台。'),text('Unlock this private link with the password you chose when creating the group.','以建立群組時設定的密碼解鎖此私人連結。'));const card=el('form',undefined,'card narrow');app.append(card);const pw=field(card,text('Organizer password','主辦者密碼'),el('input'));pw.type='password';pw.required=true;pw.maxLength=128;pw.autocomplete='current-password';const b=el('button',text('Unlock group','解鎖群組'));b.type='submit';const loginActions=el('div',undefined,'actions');loginActions.append(b);card.append(loginActions);card.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;b.disabled=true;try{const result=await api('/api/groups/'+groupId+'/login','POST',{password:pw.value});organizerSession=result.sessionToken;pw.value='';await refresh()}catch(e){error(e.message,card)}finally{busy=false;b.disabled=false}});card.append(el('p',text('Do not share this organizer link. Participants use a separate join link and never need this password.','請勿分享主辦者連結。參加者使用另一條加入連結，毋須此密碼。'),'small'))}
function orderForm(extra=false,editing=false){view=editing?'edit':extra?'extra':'order';loadDraft();cart=draft?.items|| (editing?own.items.map(i=>({...i})):[]);
 intro(extra?text('Add an organizer extra.','加入主辦者追加登記。'):editing?text('Update your request.','修改你的登記。'):group.title,extra?text('Extra requests are organizer-only and can be added after cutoff. Participant changes stay locked.','追加登記只供主辦者使用，可於截單後新增。參加者修改仍保持鎖定。'):group.welcome||text('Choose your drink. Your organizer will bring it back and distribute by name.','選擇飲品；主辦者會帶回並按姓名分發。'));
 const status=el('div',undefined,'status-bar');status.append(el('span',group.open?text('Taking requests','接受登記'):text('Requests locked','登記已鎖定'),'badge'),el('span',text('Cutoff: ','截單：')+localTime(group.cutoff)));app.append(status);
 if((!extra&&!group.open)||(editing&&!own.canEdit)){app.append(el('div',text('The cutoff has passed or requests are locked. Please contact your organizer.','截單時間已到或登記已鎖定，請聯絡主辦者。'),'card'));if(editing)app.append(button(text('Back to my request','返回我的登記'),receipt,true));return;}
 const layout=el('div',undefined,'order-layout'),builder=el('div',undefined,'card'),review=el('div',undefined,'card review');layout.append(builder,review);app.append(layout);
 const name=field(builder,text('Your name (required for distribution)','姓名（必填，供分發使用）'),el('input'));name.maxLength=60;name.required=true;name.autocomplete='name';name.value=draft?.name||(editing?own.name:'');name.addEventListener('input',()=>saveDraft(name.value));
 builder.append(el('h2',text('Choose your drink','選擇飲品')));const grid=el('div',undefined,'drink-grid');builder.append(grid);let selected=cart[0]?.drink||menu.drinks.find(d=>!group.unavailable.includes(d.id))?.id,inputs={};const custom=el('div',undefined,'customization');builder.append(custom);
 const renderCustom=()=>{custom.replaceChildren();const d=menu.drinks.find(d=>d.id===selected);if(!d)return;custom.append(el('h3',drinkName(d.id)));const options=el('div',undefined,'row');custom.append(options);inputs={};for(const [key,title,values]of[['size',text('Size preference','杯型偏好'),d.sizes],['temperature',text('Temperature','溫度'),d.temperatures],['milk',text('Milk preference','奶類偏好'),d.milk],['sweetness',text('Sweetness preference','甜度偏好'),d.sweetness]]){const c=el('div');options.append(c);inputs[key]=field(c,title,select(values,values.map(valueName)))}const quantity=field(custom,text('Cups','杯數'),el('input'));quantity.type='number';quantity.min=1;quantity.max=12;quantity.value=1;
 custom.append(button(text('Add to request +','加入登記 +'),()=>{const q=Number(quantity.value);if(!Number.isInteger(q)||q<1||q>12)return error(text('Choose 1–12 cups.','請選擇 1–12 杯。'),custom);if(cart.length>=12||cart.reduce((s,i)=>s+i.quantity,0)+q>24)return error(text('Maximum 12 items and 24 cups per request.','每筆登記最多 12 項、24 杯。'),custom);cart.push({drink:selected,...Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value])),quantity:q});saveDraft(name.value);renderReview()}));};
 const renderGrid=()=>{grid.replaceChildren();for(const [category,en,zh] of [['espresso','Espresso classics','濃縮咖啡經典'],['brewed','Brewed & cold coffee','即磨及冷萃咖啡'],['tea-chocolate','Tea & chocolate','茶及朱古力'],['frappuccino','Frappuccino','星冰樂']]){const section=el('section',undefined,'menu-category');section.append(el('h3',text(en,zh)));const choices=el('div',undefined,'drink-choices');menu.drinks.filter(d=>d.category===category).forEach(d=>{const b=button('',()=>{selected=d.id;renderGrid();renderCustom()},true);b.className='drink-option'+(selected===d.id?' selected':'');b.disabled=group.unavailable.includes(d.id);b.setAttribute('aria-pressed',String(selected===d.id));b.setAttribute('aria-label',drinkName(d.id));b.append(el('strong',drinkName(d.id)),el('span',b.disabled?text('Unavailable','暫無供應'):d.temperatures.map(valueName).join(' / '),'small'));choices.append(b)});section.append(choices);grid.append(section)}};renderGrid();renderCustom();
 function renderReview(){review.replaceChildren(el('h2',text('Your request','你的登記')));if(!cart.length)review.append(el('p',text('Add a drink to get started.','先加入一款飲品。'),'small'));cart.forEach((i,index)=>{const row=el('div',undefined,'item'),label=el('div');label.append(el('strong',`${i.quantity} × ${drinkName(i.drink)}`),el('p',[i.size,i.temperature,i.milk,i.sweetness].map(valueName).join(' · '),'small'));row.append(label,button(text('Remove','移除'),()=>{cart.splice(index,1);saveDraft(name.value);renderReview()},true));review.append(row)});const cups=cart.reduce((s,i)=>s+i.quantity,0);review.append(el('p',`${cups} ${text('cups','杯')}`,'cup-total'));const submit=button(editing?text('Save changes','儲存修改'):text('Submit request →','提交登記 →'),async()=>{
  if(busy)return;if(!name.value.trim()){name.focus();return error(text('Please enter your name.','請輸入姓名。'),review)}if(!cart.length)return error(text('Add at least one drink.','請加入至少一款飲品。'),review);saveDraft(name.value);busy=true;submit.disabled=true;submit.textContent=text('Saving…','儲存中…');
  try{if(editing){try{await api(`/api/groups/${groupId}/orders/${orderId}`,'PUT',{name:name.value,items:cart,version:own.version})}catch(e){const saved=await api(`/api/groups/${groupId}/orders/${orderId}`);if(saved.name!==name.value.trim()||JSON.stringify(saved.items)!==JSON.stringify(cart))throw e;}sessionStorage.removeItem(draftKey());own=await api(`/api/groups/${groupId}/orders/${orderId}`);receipt();}
  else{const saved=await api(`/api/groups/${groupId}/orders`,'POST',draft);sessionStorage.removeItem(draftKey());if(extra){await refresh()}else{navigate(link(draft.editToken,{o:saved.id}));}}
  }catch(e){error(e.message,review);submit.disabled=false;submit.textContent=text('Retry saving','重試儲存')}finally{busy=false}
 });submit.disabled=!cart.length;review.append(submit,el('p',text('Your name and request are visible only to the organizer and your private edit link. Save that link to edit or cancel before cutoff.','主辦者及你的私人修改連結可查看姓名和登記。請保留該連結，以便截單前修改或取消。'),'small'));}
 renderReview();app.append(notice(),retentionNotice());if(extra)app.append(button(text('Back to organizer','返回主辦者頁面'),organizer,true));if(editing)app.append(button(text('Back to my request','返回我的登記'),receipt,true));
}
function receipt(){view='receipt';intro(own.status==='cancelled'?text('Your request is cancelled.','你的登記已取消。'):text('You’re on the coffee list.','已加入飲品清單。'),text('This is your private request link. Your organizer buys the drinks and distributes them by name.','這是你的私人登記連結。主辦者會購買飲品並按姓名分發。'));const card=el('div',undefined,'card narrow');app.append(card);card.append(el('h2',own.name),el('p',text('Submitted: ','提交：')+localTime(own.submittedAt),'small'),el('p',text('Cutoff: ','截單：')+localTime(own.cutoff),'small'),el('span',own.status==='cancelled'?text('Cancelled','已取消'):own.status==='collected'?text('Distributed','已分發'):text('Request saved','已儲存登記'),'badge'));own.items.forEach(i=>card.append(el('p',`${i.quantity} × ${itemName(i)}`)));card.append(button(text('Copy my private edit link','複製我的私人修改連結'),()=>copy(location.href,card),true),el('p',text('Keep this private. Anyone with this link can view your request and change it before cutoff. Losing it means the organizer must assist you.','請勿公開此連結。持有人可查看登記，並在截單前修改。遺失連結時請聯絡主辦者。'),'note'));
 const actions=el('div',undefined,'actions');card.append(actions);if(own.canEdit)actions.append(button(text('Edit request','修改登記'),()=>orderForm(false,true)),button(text('Cancel request','取消登記'),async()=>{if(!confirm(text('Cancel your entire drink request?','取消整筆飲品登記？')))return;if(busy)return;busy=true;try{try{await api(`/api/groups/${groupId}/orders/${orderId}`,'DELETE',{version:own.version})}catch(e){const saved=await api(`/api/groups/${groupId}/orders/${orderId}`);if(saved.status!=='cancelled')throw e}await refresh()}catch(e){error(e.message,card)}finally{busy=false}},true));else card.append(el('p',text('Changes are locked after cutoff, cancellation or distribution.','截單、取消或分發後，修改會鎖定。'),'small'));actions.append(button(text('Refresh status','更新狀態'),refresh,true));app.append(retentionNotice())}
function aggregates(){const totals=new Map();for(const o of group.orders.filter(o=>o.status!=='cancelled'))for(const i of o.items){const key=variantKey(i);if(!totals.has(key))totals.set(key,{...i,quantity:0});totals.get(key).quantity+=i.quantity}return[...totals.values()]}
function organizer(){view='organizer';intro(group.title,text('Collect requests, buy together, bring them back. Your private desk for the coffee run.','收集登記，統一購買，再帶回分發。這是你的私人工作台。'));
 const top=el('div',undefined,'status-bar');top.append(el('span',group.open?text('Taking requests','接受登記'):text('Participant changes locked','參加者修改已鎖定'),'badge'),el('span',text('Cutoff: ','截單：')+localTime(group.cutoff)));app.append(top);
 const links=el('section',undefined,'card no-print');app.append(links);links.append(el('h2',text('Invite your group','邀請參加者')));const join=link(group.participantLink),share=el('input');share.readOnly=true;share.value=join;share.setAttribute('aria-label',text('Participant join link','參加者加入連結'));const shareLayout=el('div',undefined,'share-layout'),left=el('div');left.append(share,button(text('Copy join link','複製加入連結'),()=>copy(join,links),true),el('p',text('Share this link or QR. Keep your organizer URL and password private.','可分享此連結或 QR；請保管主辦者網址及密碼。'),'small'));shareLayout.append(left);
 const qrWrap=el('div',undefined,'qr');if(typeof qrcode==='function'){const qr=qrcode(0,'M');qr.addData(join,'Byte');qr.make();const img=el('img');img.src=qr.createDataURL(4,16);img.alt=text('QR code for participant join link','參加者加入連結 QR code');qrWrap.append(img)}else qrWrap.append(el('p',text('QR unavailable. Use the link.','QR 暫時無法使用，請分享連結。')));shareLayout.append(qrWrap);links.append(shareLayout);
 const actions=el('div',undefined,'actions');links.append(actions);actions.append(button(text('Refresh requests','更新登記'),refresh,true),button(text('Add extra request','追加登記'),()=>orderForm(true)),button(text('Group settings','群組設定'),settingsView,true),button(text('Lock organizer desk','鎖定工作台'),async()=>{try{await api('/api/groups/'+groupId+'/logout','POST',{});organizerSession='';group=null;login()}catch(e){error(e.message,links)}},true));
 const rows=aggregates(),cups=rows.reduce((n,i)=>n+i.quantity,0),active=group.orders.filter(o=>o.status!=='cancelled');const known=rows.filter(i=>group.estimates.some(e=>variantKey(e)===variantKey(i))),unknownCups=rows.filter(i=>!group.estimates.some(e=>variantKey(e)===variantKey(i))).reduce((n,i)=>n+i.quantity,0),minor=known.reduce((n,i)=>n+group.estimates.find(e=>variantKey(e)===variantKey(i)).minor*i.quantity,0);
 const stats=el('div',undefined,'stats');for(const [n,label]of[[cups,text('cups to buy','待購杯數')],[active.length,text('active requests','有效登記')],[active.filter(o=>o.status==='collected').length,text('distributed','已分發')]]){const c=el('div',undefined,'stat');c.append(el('strong',String(n)),el('span',label));stats.append(c)}app.append(stats);
 const summary=el('section',undefined,'card');app.append(summary);summary.append(el('h2',text('Counter buying list','門市購買清單')),el('p',`${group.region} · ${group.store}`,'small'));
 if(!rows.length)summary.append(el('p',text('No requests yet. Share the join link to begin.','暫無登記，請分享加入連結。')));rows.forEach(i=>{const row=el('div',undefined,'item'),c=el('div');c.append(el('strong',`${i.quantity} × ${drinkName(i.drink)}`),el('p',[i.size,i.temperature,i.milk,i.sweetness].map(valueName).join(' · '),'small'));if(group.unavailable.includes(i.drink))c.append(el('span',text('Marked unavailable — follow up','已標記缺貨，請跟進'),'warning'));row.append(c);summary.append(row)});
 summary.append(el('p',unknownCups?`${text('Total cost: unknown. Known estimate subtotal: ','總金額：未知。已知估算小計：')}${group.currency} ${(minor/100).toFixed(2)} · ${unknownCups} ${text('cups unpriced','杯未有價格')}`:`${text('Estimated total: ','估算總額：')}${group.currency} ${(minor/100).toFixed(2)}`,'cost-total'),el('p',text('Organizer-entered estimates only; confirm exact variants and current prices at your store. Participants never see costs.','價格由主辦者輸入，僅供估算。請向門市確認當日價格及選項；參加者不會看到金額。'),'small'));
 const counterText=()=>group.title+'\n'+group.region+' · '+group.store+'\n'+rows.map(i=>`${i.quantity} × ${itemName(i)}${group.unavailable.includes(i.drink)?' [UNAVAILABLE]':''}`).join('\n')+'\n'+text('Confirm all preferences with the store.','所有偏好須向門市確認。');const sa=el('div',undefined,'actions');summary.append(sa);sa.append(button(text('Copy buying list','複製購買清單'),()=>copy(counterText(),summary),true),button(text('Print lists','列印清單'),()=>window.print(),true),button(text('Enter cost estimates','輸入價格估算'),priceView,true));
 const people=el('section',undefined,'card');app.append(people);people.append(el('h2',text('Bring back & distribute','帶回及按姓名分發')));for(const o of group.orders){const row=el('div',undefined,'item person'+(o.status==='cancelled'?' cancelled':'')),c=el('div');c.append(el('h3',o.name),el('p',localTime(o.submitted_at)+(o.extra?text(' · Organizer extra',' · 主辦者追加'):''),'small'));o.items.forEach(i=>c.append(el('p',`${i.quantity} × ${itemName(i)}`)));row.append(c);if(o.status!=='cancelled'){const b=button(o.status==='collected'?text('Distributed ✓','已分發 ✓'):text('Mark distributed','標記已分發'),async()=>{b.disabled=true;try{await api(`/api/groups/${groupId}/orders/${o.id}`,'PATCH',{version:o.version,status:o.status==='collected'?'pending':'collected'});await refresh()}catch(e){error(e.message,people);b.disabled=false}},o.status==='collected');b.classList.add('no-print');row.append(b)}else row.append(el('span',text('Cancelled','已取消'),'badge'));people.append(row)}
 app.append(retentionNotice(),notice());
}
function settingsBody(overrides={}){return{title:group.title,welcome:group.welcome,region:group.region,store:group.store,cutoff:group.cutoff,closed:group.closed,unavailable:group.unavailable,estimates:group.estimates,...overrides}}
function settingsView(){view='settings';intro(text('Set up your coffee run.','設定你的飲品群組。'),text('Store and purchase settings are private. Participants see your title, welcome message and cutoff.','門市及購買設定屬私人資料。參加者只會看到名稱、歡迎訊息及截單時間。'));const card=el('form',undefined,'card');app.append(card);const title=field(card,text('Group name','群組名稱'),el('input'));title.value=group.title;title.required=true;title.maxLength=80;const welcome=field(card,text('Participant welcome message','參加者歡迎訊息'),el('textarea'));welcome.value=group.welcome;welcome.maxLength=500;
 const region=field(card,text('Private purchase region','私人購買地區'),select(['HK','MO'],['Hong Kong · HKD','Macau · MOP']));region.value=group.region;
 const store=field(card,text('Private store / purchase location','私人門市 / 購買地點'),el('input'));store.value=group.store;store.required=true;store.maxLength=120;
 const cutoff=field(card,text('Cutoff (Macau time UTC+8)','截單（澳門時間 UTC+8）'),el('input'));cutoff.type='datetime-local';cutoff.value=toInput(group.cutoff);cutoff.required=true;
 const closed=field(card,text('Participant collection','參加者登記狀態'),select(['open','closed'],[text('Accept until cutoff','接受登記至截單'),text('Close now','立即關閉')]));closed.value=group.closed?'closed':'open';
 card.append(el('h2',text('Unavailable drinks','暫無供應飲品')));const checks=new Map();menu.drinks.forEach(d=>{const label=el('label',undefined,'unavailable'),c=el('input');c.type='checkbox';c.checked=group.unavailable.includes(d.id);checks.set(d.id,c);label.append(c,el('span',drinkName(d.id)));card.append(label)});
 const b=el('button',text('Save settings','儲存設定'));b.type='submit';const actions=el('div',undefined,'actions');actions.append(b,button(text('Back','返回'),organizer,true));card.append(actions);card.addEventListener('submit',async e=>{e.preventDefault();b.disabled=true;try{const newCutoff=toInput(group.cutoff)===cutoff.value?group.cutoff:fromInput(cutoff.value);if(region.value!==group.region&&group.estimates.length&&!confirm(text('Changing currency clears all saved price estimates. Continue?','更改幣種會清除已存價格估算。繼續？')))return;await api('/api/groups/'+groupId,'PATCH',settingsBody({title:title.value,welcome:welcome.value,region:region.value,store:store.value,cutoff:newCutoff,closed:closed.value==='closed',unavailable:[...checks].filter(([,c])=>c.checked).map(([id])=>id),estimates:region.value===group.region?group.estimates:[]}));await refresh()}catch(e){error(e.message,card)}finally{b.disabled=false}});
 card.append(retentionNotice());app.append(button(text('Delete this group and all data','刪除群組及全部資料'),async()=>{if(!confirm(text('Permanently delete this group, requests and settings?','永久刪除此群組、登記及設定？')))return;try{await api('/api/groups/'+groupId,'DELETE',{});location.href=frontendBase.href}catch(e){error(e.message,card)}},true));
}
function priceView(){view='prices';intro(text('Private cost estimates.','私人價格估算。'),text('Enter store-confirmed estimates for the exact variants requested. Unknown stays unknown.','請按已登記的確切選項輸入門市確認的估算價。未有價格會保持未知。'));const card=el('form',undefined,'card');app.append(card);const inputs=[];const rows=aggregates();if(!rows.length)card.append(el('p',text('Price variants appear after requests arrive.','有登記後便會顯示價格選項。')));
 for(const i of rows){const c=el('section',undefined,'price-row');c.append(el('h3',`${i.quantity} × ${itemName(i)}`));const existing=group.estimates.find(e=>variantKey(e)===variantKey(i));const amount=field(c,group.currency+' '+text('unit estimate (blank = unknown)','每杯估算（留空 = 未知）'),el('input'));amount.type='number';amount.min=0;amount.max=1000;amount.step='.01';amount.value=existing?(existing.minor/100).toFixed(2):'';const source=field(c,text('Source / store confirmation note','來源 / 門市確認備註'),el('input'));source.maxLength=120;source.value=existing?.source||'';const date=field(c,text('Checked date','確認日期'),el('input'));date.type='date';date.value=existing?.checkedAt||new Date().toISOString().slice(0,10);inputs.push({i,amount,source,date});card.append(c)}
 const b=el('button',text('Save private estimates','儲存私人估算'));b.type='submit';const actions=el('div',undefined,'actions');actions.append(b,button(text('Back','返回'),organizer,true));card.append(actions);card.addEventListener('submit',async e=>{e.preventDefault();b.disabled=true;try{const variants=new Set(rows.map(variantKey));const estimates=group.estimates.filter(e=>!variants.has(variantKey(e)));for(const {i,amount,source,date}of inputs){if(amount.value==='')continue;const minor=Math.round(Number(amount.value)*100);if(!source.value.trim()||!date.value)throw new Error(text('Add a source and checked date for each price.','每個價格均須填寫來源及確認日期。'));estimates.push({...i,minor,source:source.value,checkedAt:date.value})}await api('/api/groups/'+groupId,'PATCH',settingsBody({estimates}));await refresh()}catch(e){error(e.message,card)}finally{b.disabled=false}})
}
async function refresh(){try{group=await api('/api/groups/'+groupId);if(orderId){own=await api(`/api/groups/${groupId}/orders/${orderId}`);receipt()}else if(group.role==='organizer')organizer();else orderForm()}catch(e){if(e.status===401&&isAdmin){organizerSession='';group=null;login();return}intro(text('This link needs attention.','此連結需要檢查。'),e.message);app.append(button(text('Try again','重試'),refresh,true));if(orderId)app.append(el('p',text('Requests clear daily at 23:59 Macau time. Ask your organizer for a current join link if this request was cleared.','登記每天澳門時間 23:59 清除。如已清除，請向主辦者索取當日加入連結。'),'small'))}}
function applyLanguage(){document.documentElement.lang=lang==='en'?'en':'zh-Hant';document.querySelector('#language').textContent=lang==='en'?'繁體中文':'English'}
document.querySelector('#language').addEventListener('click',()=>{const nameInput=app.querySelector('input[autocomplete="name"]');if(nameInput&&view!=='receipt')saveDraft(nameInput.value);lang=lang==='en'?'zh':'en';sessionStorage.setItem('language',lang);applyLanguage();if(!menu)return;({home,login,organizer,settings:settingsView,prices:priceView,receipt,order:()=>orderForm(),extra:()=>orderForm(true),edit:()=>orderForm(false,true)}[view]||home)()});
applyLanguage();(async()=>{try{menu=await api('/api/menu','GET',undefined,null);if(groupId&&access)await refresh();else home()}catch(e){error(e.message);app.append(button(text('Reload','重新載入'),()=>location.reload(),true))}})();
